//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhi
    {
        public int MaHocPhi { get; set; }
        public Nullable<int> HocKi { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<int> MaSV { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
    }
}
