//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhan
    {
        public int MaHocPhan { get; set; }
        public Nullable<int> SoTiet { get; set; }
        public string ThoiGian { get; set; }
        public Nullable<int> MaMonHoc { get; set; }
        public Nullable<int> MaSV { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
